// Transcripciones de las lecciones
const transcripciones = {
    leccion1: `Como punto de inicio de nuestro mensaje esta mañana quisiera compartir con ustedes 2 Timoteo capítulo 3, que será el punto de partida basado en lo que este texto afirma.

Segunda Timoteo 3:16-17 dice: “Toda la Escritura es inspirada por Dios, y útil para enseñar, para redargüir, para corregir, para instruir en justicia,  a fin de que el hombre de Dios sea perfecto, enteramente preparado para toda buena obra”. Toda la Escritura está inspirada por Dios.

Hemos visto con detalle estos dos versículos en el marco del contexto de este capítulo. Y hoy, puede que me desvíe un poco de este texto para observar otras porciones de la Escritura, con el fin de enriquecer nuestro entendimiento de lo que significa tener en nuestras manos la Palabra del Dios vivo. 

Espero que usted sienta un alto aprecio por la Escritura. No como un fetiche, sino porque es el tesoro más grande aparte de Dios mismo que tenemos. Es Su palabra, Su propia revelación. Cuando la gente me pregunta por qué es que yo sistemáticamente enseño libro tras libro, por qué es que presto tanta atención a los detalles, a cada versículo, a cada frase y me detengo en todas las palabras, es porque entiendo que son las palabras que Dios mismo nos revela. Y es necesario que esas palabras sean presentadas, enseñadas y comprendidas por todos nosotros. En Grace Community Church estamos comprometidos al ministerio bíblico, al método de predicación expositiva, porque creemos que esta es la Palabra del Dios vivo. Dios se ha revelado en Su libro. Y cuando usted lee las palabras de la Biblia, está leyendo las palabras de la boca de Dios. Esa es una tremenda realidad. Eso nos da confianza en todo lo que hacemos. También nos obliga a la obediencia y sumisión de todo lo que la Escritura enseña.

Vamos a hablar un poco acerca de lo que significa que "toda la Escritura es inspirada por Dios". ¿Qué es inherente a ese pensamiento? Deseo mostrarle un par de Escrituras para enriquecer esto; y luego deseo compartir algunas otras cosas que están en mi corazón.

Busque en su Biblia Hebreos, capítulo 1. Vamos a ver el primer versículo y la primera parte del segundo. Hebreos, capítulo 1, empieza así: "Dios, habiendo hablado muchas veces y de muchas maneras en otro tiempo a los padres por los profetas,  en estos postreros días nos ha hablado por el Hijo”. Esa es la afirmación en la que quiero que se enfoquen. No tengo la intención de agotar todas las ramificaciones de esa declaración; pero en su simplicidad, es muy clara y muy profunda. Nos está dando la esencia de la revelación. Marque la palabra; revelación en su sentido simple significa revelar... dar a conocer algo que antes no se conocía, hacer comprensible algo que no se entendía, revelar la verdad nunca antes conocida. Dios se ha revelado a Sí mismo. Y aquí hay una declaración con respecto a la revelación. Dios habló hace mucho tiempo y Dios ha hablado en estos últimos días.

El escritor de Hebreos está en efecto diciendo que Dios habló en dos ocasiones. Él habló una vez hace mucho tiempo y habla en estos últimos días a través de Su Hijo. Considero justo evaluar el hecho que él aquí tiene en mente la revelación del Antiguo Testamento y la revelación del Nuevo Testamento. Dios habló hace mucho tiempo a los padres judíos. Esos fueron los profetas del Antiguo Testamento, los que recibieron la Palabra de Dios hace mucho tiempo bajo el antiguo pacto. Él habló a los padres por medio de los profetas.

Habló también –dice- de muchas maneras, polutropos. Eso significa que a través de visiones,  profecías, parábolas, símbolos, ceremonias, teofanía y a veces por medio de una voz audible. Él incluso escribió con Su dedo sobre piedra. Hay muchas maneras en las que Dios habló muchas cosas, recopiladas en muchos textos, puestas en muchos libros; y habló en la antigüedad por medio de los profetas. Esa es una aseveración en relación con el hecho de que en el Antiguo Testamento, Dios es quien está hablando.

El Antiguo Testamento no es una compilación de sabiduría de hombres ancianos; no es una compilación de los mejores pensamientos religiosos; un conjunto de buenas meditaciones de gente piadosa. El Antiguo Testamento es la Palabra de Dios. No es el pensamiento de ningún hombre, ni bueno ni piadoso ni mayor. Es la Palabra de Dios. Y el escritor de Hebreos dice que Dios habló. Era Dios hablándole a los patriarcas por medio de lo profetas. Estos últimos días, desde la llegada de Cristo, Él ha hablado nuevamente. Ha hablado a través del Hijo. Los Evangelios registran a Dios hablando a través de Su Hijo -Mateo, Marcos, Lucas y Juan. El libro de Hechos, Dios hablando a través de la proclamación del mensaje de Su Hijo. Las epístolas, Dios hablando a través del entendimiento profundo del significado de la vida y el ministerio de Su Hijo. Y en Apocalipsis, la consumación, cuando el Hijo regresa en gloria. La consumación de la comunicación de Dios a este mundo.

Por lo tanto, el Antiguo Testamento es Dios hablando y revelándose. El Nuevo Testamento es Dios hablando y revelando a Su Hijo. El Antiguo Testamento es la auto-revelación de Dios; y ese es el tema. Desde Génesis hasta Malaquías, el personaje principal es Dios. Es la revelación de Dios, quién Él es; cuáles son Sus atributos; cuáles son Sus actitudes; cómo Él reacciona a cada situación humana posible; cómo es Él; qué hace. No es la historia del hombre. Ni la historia de Israel. Esas historias están ahí, pero es la revelación de Dios. Y vemos cómo Dios se revela a través del hombre, a través de la historia, a través de Israel y a través de todo lo que sucede. Los atributos de Dios están a veces enumerados de manera muy clara como lo están en los Salmos. Por otra parte, a veces vemos Sus atributos de manera muy clara y Él ni siquiera es mencionado; tal como en el libro de Ester en donde no se menciona a Dios y sin embargo es la fuerza y el carácter dominante a lo largo de todo el libro.

El Antiguo Testamento es la revelación de Dios para mostrarle al hombre cómo Él es, quién es, qué tolera y qué no, cómo Él desea la santidad y castiga el pecado. El Nuevo Testamento es Dios revelando a Su Hijo en la vida de Él, en Su mensaje, en el entendimiento del trabajo de Su Hijo y en la culminación y llegada de Su Hijo para establecer Su Reino eterno. En ambos casos, en el Antiguo y en el Nuevo Testamento, Dios habló. Y lo que tenemos es Su Palabra, no la palabra del hombre.

Los escritores del Nuevo Testamento escribieron la Palabra de Dios. Jesús prometió que Él nos ensenaría todas las cosas, nos recordaría todo lo que nos había dicho; que nos guiaría a la Verdad y nos mostraría las cosas por venir. Y al prometerlo, dio a los apóstoles, y con ellos a los otros escritores del Nuevo Testamento, la promesa de la inspiración divina. Tanto ellos, como también los profetas del Antiguo Testamento, escribirían la Palabra de Dios.

Y por lo tanto, lo que tenemos en nuestras manos no es la palabra del hombre, ni de hombres religiosos, ni de hombres sabios y piadosos; sino que es la Palabra de Dios. Hebreos 1 y 2 habla de revelación, la revelación de Dios.

¿Qué proceso utilizó Dios para revelarse? Miremos otro texto, 2 Pedro. Veamos el proceso que Dios utilizó, conocido como inspiración. Segunda Pedro 1:20 dice: “Entendiendo primero esto, que ninguna profecía” -la palabra profecía aquí tiene un sentido muy genérico y no significa algún tipo de predicción del futuro, sino mensaje- “ninguna profecía de la Escritura es de interpretación privada”,epilyseos. Fíjense en esto, ningún mensaje de la Escritura es un tema de epilyseos propio.

¿Qué significa eso? Ningún mensaje de la Escritura es asunto de inspiración propia. Es decir, la Escritura no proviene de hombres inspirados en el sentido de que algunos son como iluminados genios religiosos. El caso genitivo sugiere aquí que Pedro tiene en mente la fuente o el origen de la Escritura; y él no está realmente hablando de interpretar la Biblia en el sentido que usted describa lo que significa; sino que él está hablando sobre el origen de modo de poder decir esto "Ninguna profecía de la Escritura tiene el origen en la propia mente." Ningún mensaje de la Escritura proviene de ninguna fuente humana; esa es la idea.

"Porque", dice el versículo 21, "nunca la profecía fue traída por voluntad humana, sino que los santos hombres de Dios hablaron siendo inspirados por el Espíritu Santo". La Escritura no es producto de los hombres. No es producto de la voluntad de los hombres. Muy claro y vital. Ningún mensaje se ha hecho nunca -verbo en pasivo indicativo –phero-que significa soportar, llevar adelante, transmitir, producir, producir, llevar. Ningún mensaje fue nunca transmitido, llevado, producido por un acto de voluntad humana, sino que los hombres fueron llevados -phero, mismo verbo- por el Espíritu Santo para hablar de Dios. Fueron llenados por el Espíritu Santo. La idea es como poner las velas al viento en un barco y ser arrastrado por la brisa. El Espíritu de Dios los movilizó. Y eso nos expresa el proceso.

El contenido de la Biblia es la revelación. El proceso mediante el cual fue escrito el contenido se llama inspiración. Y no hubo un alto nivel de actividad humana, ni siquiera un alto nivel de actividad humana religiosa. Los hombres estaban en el proceso, pero no se originó con ellos y no vino de su deseo y su voluntad. Fueron utilizados a medida que eran llevados por el Espíritu Santo y eran capacitados para hablar de Dios. Hablaron palabras divinas. Dios los usó. Era su personalidad. Era su historia, algunas de sus ideas, sus experiencias, sus percepciones; pero cada palabra era la palabra de Dios. Ese es el milagro de la inspiración. Los hombres fueron usados, inspirados por el Espíritu Santo, y hablaron de parte de Dios. Eso es lo que dice la Escritura.

Por lo tanto, al momento de tomar su Biblia, usted no está leyendo la palabra de los hombres, está leyendo la Palabra de Dios que fue escrita por hombres que fueron movidos durante el proceso por el poder del Espíritu Santo. No separado de sus personalidades, ni de sus experiencias, ni de su vocabulario, de su corazón, pasión y fuerza, sino integrando todo eso en el poder del Espíritu de Dios y nunca transigiendo la verdad de que cada palabra provino de Dios. Un gran y glorioso milagro, tan vital.

Por lo tanto, Dios habló en el Antiguo Testamento a los Patriarcas por medio de los profetas en muchas formas y en muchas partes. Y Dios ha hablado en el Nuevo Testamento por medio de Su Hijo en los Evangelios; y luego acerca de su Hijo, en el resto del Nuevo Testamento. El proceso por el cual Dios nos dio esa revelación es la inspiración; y la inspiración es Dios poniendo Su revelación, por así decirlo, en las manos de los hombres, para primero ser divulgada y proclamada; y luego ser escrita a medida que eran energizados, llevados por el Espíritu Santo. Se utilizó a hombres; y sin embargo, nunca fue violada una sola palabra de Dios. La totalidad de la Escritura, pasa graphe, toda la Escritura, cada Escritura, es theopneustos, inspirada por Dios. La redacción de la Escritura es el aliento de Dios. La totalidad de la misma, de acuerdo a Romanos 3:2, se llama la Palabra de Dios. Cuando Pablo habla del beneficio de Israel -lo que ellos tenían, que los distinguia de otras naciones, a lo que hace referencia al Antiguo Testamento-  menciona a la palabra de Dios... los discursos de Dios... las palabras de Dios.

Y Jeremías es un buen ejemplo de este proceso. Jeremías, llamado por Dios desde antes de su nacimiento, dice en el capítulo 1 versículo 4: "Vino, pues, palabra de Jehová a mí, diciendo: Antes que te formase en el vientre te conocí, y antes que nacieses te santifiqué, te di por profeta a las naciones. Y yo dije: ¡Ah! ¡Ah, Señor Jehová! He aquí, no sé hablar, porque soy niño". Versículo 9: "Y extendió Jehová Su mano y tocó mi boca, y me dijo Jehová: He aquí he puesto Mis palabras en tu boca". ¡Qué maravillosa declaración! He puesto Mis palabras en tu boca; esa era la promesa para los escritores de la Escritura. Toda la Escritura es inspirada por Dios. Toda Escritura Santa viene de Dios.

Somos conscientes de eso. Somos conscientes del atributo divino de la Escritura. La iglesia primitiva lo reconoció. A pesar de que no fue sino hasta 393, 397, en el Concilio de Hipona, el Concilio de Cartago -en ese tiempo- que la iglesia estableció oficialmente el canon de la Escritura integralmente. No pasó mucho tiempo antes de que la gente lo reconociera. La Iglesia no ha inventado el canon de las Escrituras más de lo que Newton inventó la ley de la gravedad. Newton descubrió la gravedad que Dios inventó; y la Iglesia descubrió, desde los primeros inspirados documentos, que Dios mismo fue quien los escribió. Y a pesar de que pasó algún tiempo antes de que alguna iglesia estableciera algún sello oficial a toda ella, para la iglesia primitiva era absolutamente claro qué era la Palabra de Dios y qué no lo era. Y hay todo tipo de libros erróneos que han sido dejados fuera. Pero lo que era la Palabra de Dios, era la Palabra de Dios. Dios es el autor de las Escrituras.

De hecho, con frecuencia las palabras Dios y Escritura se utilizan indistintamente. En Gálatas: "Y la Escritura, previendo que Dios había de justificar por la fe a los gentiles, dio de antemano la buena nueva a Abraham, diciendo: En ti serán benditas todas las naciones." La Escritura dice que en él serán benditas todas las naciones. En Génesis 12 vemos que Dios lo dijo. Dios dijo, la Escritura dijo, es lo mismo. Lo que la Escritura dice, Dios dice.

En Hechos capítulo 13 es una nota más interesante en el sermón del apóstol Pablo. Él dice en el versículo 32: "Y nosotros también os anunciamos el Evangelio de aquella promesa hecha a nuestros padres,  la cual Dios ha cumplido a los hijos de ellos, a nosotros, resucitando a Jesús; como está escrito también en el Salmo segundo: Mi hijo eres tú, Yo te he engendrado hoy. Y en cuanto a que le levantó de los muertos para nunca más volver a corrupción, lo dijo así: Os daré las misericordias fieles de David. Por eso dice también en otro salmo: No permitirás que tu Santo vea corrupción. Porque a la verdad David, habiendo servido a su propia generación según la voluntad de Dios, durmió, y fue reunido con sus padres, y vio corrupción. Mas aquel a quien Dios levantó, no vio corrupción". En otras palabras, Dios está hablando en los Salmos. Y eso es exactamente lo que el apóstol está afirmando. Cuando los Salmos hablan, Dios habla.

En Romanos 9, versículo 17, la Escritura dice a Faraón: "Para esto mismo te he levantado," y así sucesivamente. La Escritura no dice eso en el Antiguo Testamento, Dios lo dijo, pero cuando Dios habla, es la Escritura; cuando la Escritura habla, es Dios. Encontrará esa terminología intercambiada.

Una acotación. La Biblia no dice que los escritores fueron inspirados. Ni Pablo ni Pedro lo dicen. La Escritura fue inspirada. Los hombres no tenían una habilidad sobrenatural que podían utilizar en algún momento para producir la Escritura. Solo eran inspirados cuando Dios les daba Su Palabra. El resto del tiempo, hablaban de manera independiente de cualquier inspiración. Por lo que la Biblia no sabe técnicamente de hombres inspirados, sino de palabras inspiradas. Palabras inspiradas por Dios. Ni Isaías, ni David, ni Pablo, ni Juan ni ningún otro escritor bíblico fueron inspirados como personas para escribir la Escritura cuando quisieran; hubo momentos especiales en sus vidas en los cuales Dios les dio directamente Su Palabra para ser escrita; y el resto del tiempo, lo que escribieron era propio. Entonces, los hombres no fueron inspirados, la Escritura lo es.

Dios los inspiró y ellos escribieron, palabra por palabra, lo que Dios les inspiroó. Era más que un dictado. No estaban escuchando una voz y escribiendo mecánicamente cada palabra; fluía de sus corazones, almas, mentes, emociones y experiencias. Cada palabra salió de la Palabra de Dios. A medida que Dios les inspiraba el mensaje y eran llenos del Espíritu Santo, lo expresaban y algunos de ellos, lo escribían. Un proceso milagroso, sobrenatural e inexplicable que produce en nosotros la Palabra de Dios.

Ahora voy a hablar de ello desde un punto de vista negativo, sólo para ilustrar la idea central. Y quiero señalar que cuando hablamos de que la Biblia está inspirada, no estamos diciendo que hay algunos hombres que tenían un alto nivel de capacidad humana, una especie de genios religiosos. El mundo está lleno de gente así. Ha habido genios de la música que han sido prolíficos, que eran profundos, que eran mucho más que las personas comunes y tal vez más que incluso los mejores hombres. Hubo y hay genios en la literatura, genios en la prosa y en la poesía, grandes hombres y mujeres de formidable capacidad que diríamos que son poetas, músicos, escritores, pensadores inspirados. Pero cuando hablamos de la inspiración de la Biblia, no estamos hablando de un alto nivel de desarrollo humano, no es así. No estamos hablando de hombres, como he dicho, que podían escribir en cualquier momento que quisieran la Escritura porque eran genios religiosos; no. Ninguno de ellos podía hacer eso. Sólo cuando Dios les daba lo que Él quería decir o escribir podían ellos hacerlo; y bajo el trabajo del Espíritu de Dios.

Ellos, por cierto, no han producido otra cosa, otros escritos. ¿Por qué no hay muchas cosas más escritas por Pedro? ¿Por qué no escribieron otros libros? ¿Por qué no siguieron escribiendo más y más y más si eran tan sólo genios humanos de gran nivel? Los mismos escritores de la Biblia afirman que lo que escribieron, Dios escribió, no ellos. Es curioso para mí que tenían una especie de extraño aire de seguridad. Dijeron que escribieron por Dios y nunca parecían ser conscientes al respecto. Quiero decir que si usted observa a los escritores de la Biblia, son en su mayor parte hombres analfabetos y comunes. Y sin embargo, están sumamente seguros de que escriben la Palabra de Dios. De hecho, alrededor de 4.000 veces en la Biblia, los escritores dicen estar escribiendo la Palabra de Dios. Y nunca están conscientes de ello. Quiero decir, que me imagino que en algún momento dirían: "Y esta es la Palabra de Dios, sé que parece difícil de creer que yo les estoy diciendo la Palabra exacta de Dios, pero esto es realmente cierto. No estoy hablando tonterías. Esto es realmente cierto. Verdaderamente es el Señor, Él me dijo que les dijera esto". No tiene sentido auto-justificarse. No tiene sentido auto-defenderse. Y aunque la mayoría de ellos no tenía una educación extensa y no estaba en condiciones terrenales de ser un genio literario, escribieron con esta profunda sabiduría sobrenatural profecías del futuro, cosas que sucederían que eran absolutamente precisas. Escribieron sobre la naturaleza y el carácter de Dios. Ellos escribieron de los propósitos divinos de Dios que se desarrollan en el mundo. Ellos estaban en lo cierto acerca de cada cosa que han dicho y todos ellos afirmaron que provenía de Dios; y sin embargo, nunca fueron conscientes sobre tal afirmación. Increíble... increíble. Simplemente asumieron que era la Palabra de Dios y la escribieron como tal.

Santiago describió la autoridad de las Escrituras cuando dijo en el capítulo 4, versículo 5: "¿O pensáis que la Escritura dice en vano…?" Tienen autoridad. Pablo dijo que la ley de Dios era santa, justa y buena; y lo que tenía en la mente era la ley revelada de Dios, el Antiguo Testamento. Los escritores del Nuevo Testamento afirmaron que escribieron la Palabra de Dios al igual que los escritores del Antiguo Testamento lo habían hecho. Hay alrededor de 320 citas directas del Antiguo Testamento en el Nuevo Testamento; unas 1.000 inferencias. Los escritores del Nuevo Testamento claramente creían que el Antiguo Testamento fue inspirado. También estaban convencidos de que su propio Nuevo Testamento fue inspirado. Ellos sabían que estaban escribiendo la Palabra de Dios. Y no era un alto nivel de genio humano. Ellos fueron movidos por el Espíritu de Dios para hacer lo que de otro modo nunca hubieran podido hacer.

En segundo lugar, hay personas que dicen que la Biblia fue inspirada solo en conceptos y no en las palabras reales. A través de los años, he tratado de lidiar con la gente que piensa que ellos fueron inspirados por Dios con grandes pensamientos religiosos y lo escribieron con sus propias palabras, por lo que en realidad no poseemos las palabras de Dios. Que no debemos estancarnos en una palabra sino tomar los conceptos y continuar con las ideas y cómo fluyen, sin preocuparnos por las palabras. Esas son solo detalles que se interponen en el camino. Hay personas que dicen que el Espíritu da vida y la letra mata.

Me gustaría preguntarle a alguien cómo comunicar una idea sin utilizar palabras. Creo que no comprendo. ¿Cómo podría usted, si fuera Dios, comunicar una idea sin palabras? No tiene sentido. Y cuando Moisés quiso excusarse de hablar por el Señor porque no era elocuente, Dios le dijo que Él estaría con él y le enseñaría qué decir.

Isaías dijo: “Después oí la voz del Señor, que decía…” Jeremías dijo: “Vino, pues, palabra de Jehová a mí, diciendo…” Ezequiel  escribió: “Hijo de hombre, ve y entra a la casa de Israel, y habla a ellos con Mis palabras… Hijo de hombre, toma en tu corazón todas Mis palabras que Yo te hablaré, y oye con tus oídos.” Palabras, no ideas. Amós expresó: “Entonces respondió Amós, y dijo a Amasías: No soy profeta, ni soy hijo de profeta, sino que soy boyero, y recojo higos silvestres. Y Jehová me tomó de detrás del ganado, y me dijo: Ve y profetiza a Mi pueblo Israel.”

La maravillosa experiencia de Pablo en su conversión, quien cuando estando con Ananías relata en Hechos 22: “El Dios de nuestros padres te ha escogido para que conozcas Su voluntad, y veas al Justo, y oigas la voz de Su boca.” Dios ha designado que Pablo Le escuche y comunique lo que le diga.

Juan dijo: “Yo estaba en el Espíritu en el día del Señor, y oí detrás de mí una gran voz como de trompeta, que decía… Escribe las cosas que has visto, y las que son, y las que han de ser después de estas”. Aun Cristo, el Verbo hecho carne, dijo que Él recibió Su mensaje de Su Padre. Le dijo a Cristo qué decir.

No se puede tener ideas sin palabras; ese tipo de concepto es una tontería. Es lo mismo que hablar de una melodía sin notas o música sin melodía. Es lo mismo que hablar de sol sin luz o antropología sin hombres. No hay pensamientos sin palabras.

Muy por el contrario. Mire 1 Pedro 1:10-11 por un momento, algo interesante; esto ilustra un principio. Pedro escribe con referencia a los profetas del Antiguo Testamento, que registraron la verdad sobre el Mesías. Él dice: "Los profetas que profetizaron de la gracia destinada a vosotros, inquirieron y diligentemente indagaron acerca de esta salvación, escudriñando qué persona y qué tiempo indicaba el Espíritu de Cristo que estaba en ellos…". En otras palabras, allí estaban, los profetas del Antiguo Testamento, siendo llevados por el Espíritu Santo e inspirados para hablar y escribir acerca del Mesías. Y a medida que ellos estaban hablando o escribiendo acerca del Mesías, estaban haciendo una cuidadosa búsqueda e investigación para averiguar de lo que estaban hablando. El punto es éste, no sólo la Biblia no enseña que hay pensamientos sin palabras, sino que nos enseña que a veces Dios les dio palabras sin pensamientos. No me refiero a un dictado mecánico sin sentido, pero había muchas cosas que los escritores del Antiguo Testamento escribieron que no llegaban a comprender. No es algo que ellos relataron debido a su genialidad religiosa, sino que asentaban las palabras que Dios les dio, ya fuera que las entendieran completamente o no. Y es por eso que en Mateo 24:35 dice: "El cielo y la tierra pasarán, pero Mis palabras" -no Mis pensamientos- "no pasarán."

Entonces, alguien dice que la Biblia es inspirada cuando habla de las cosas sagradas y que no lo es cuando habla de las cosas seculares como la ciencia, la historia, la geografía y demás. Algo con lo que hay que lidiar periódicamente. Hay quienes dicen que la historia de la Biblia es errónea. La geografía de la Biblia está mal. Las matemáticas de la Biblia son inexactas. Las declaraciones científicas de la Biblia son equívocas. Pero no se preocupe, la inspiración garantiza lo sagrado, no lo secular... que es como decir que Dios es bueno en las cosas religiosas, pero realmente necesita ayuda en otras áreas... no maneja bien otros datos Y hay todo tipo de personas que quiere atacar la Biblia basados en eso.

Le voy a dar un par de ejemplos curiosos. Josué 10:12, donde se relata la batalla que estaba sucediendo, se dice que en el medio de la misma el sol se detuvo. Y los críticos se han reído y burlado durante años. Dicen que la Biblia es poco científica. Si la relación entre la tierra y el sol no cambiara, querría decir que la tierra se detuvo. Pero el hecho es que si usted estaba allí ese día, le hubiera parecido como si el sol se detuviera. Y ese mismo crítico, sería el primer hombre que al levantarse de la cama en la mañana, miraría por la ventana y diría: "¡Qué hermoso amanecer!" Eso no es una salida del sol, por cierto. Pero nadie sale y dice: "¡Oh, qué hermosa tierra que gira!" Y nadie tampoco dice eso por la noche.

Y todo el tiempo decimos cosas por el estilo. Decimos que la gente vive en Australia abajo, ¿abajo de qué? Esa es una frase hecha. Un modo figurativo. Hay algunas cosas que decimos desde la perspectiva humana, que no pretenden ser afirmaciones de elementos técnicos de datos científicos.

Luego, está el relato en el libro 2 Reyes 18 de la transacción de Senaquerib con Ezequías, de 30 talentos de oro y 300 talentos de plata; la cual no parece ser un problema hasta que los arqueólogos descubrieron los registros asirios de la transacción entre ellos. El propio registro de Senaquerib; y en su cuenta había 800 talentos de plata en lugar de 300. Y los críticos dijeron que ese es el tipo de datos donde la Biblia se equivoca ya que no es cuidadosa con los números pequeños. Y luego, estudios arqueológicos posteriores han revelado que la norma de cálculo del oro era la misma en Judea y Siria pero el estándar para el cálculo de plata era diferente; y 800 talentos de Siria equivalían a 300 talentos hebreos. Exactamente lo que dice la Escritura. La Escritura habla en hebreo y el registro de Senaquerib, en sirio.

Permítanme mostrarles otro. Hay muchos más en donde la Biblia supuestamente se equivoca; y no es así si se mira con cuidado. Uno muy curioso está en Números 11:31, el cuarto libro en el Antiguo Testamento. "Y vino un viento de Jehová." Los hijos de Israel estaban en este momento deambulando por el Sinaí y tenían que ser alimentados. Y el Señor los va a alimentar. Y es muy interesante cómo Él les da de comer. Él envió un viento y trajo codornices desde el mar. El viento trajo codornices. Y las dejó en el campamento. Un día de camino a un lado, y un día de camino al otro, alrededor del campamento. Estaban en un área extensa.

Y dice que tenía dos codos de profundidad… un codo era más o menos 18 pulgadas. Así que estamos hablando aproximadamente de tres a cuatro pies. Tomemos al crítico que decidió que eran cuatro pies, y quiso hacer algunos cálculos. Dijo que esta es una de las cosas más ridículas que ha leído. ¿Un día de camino a un lado y un día de camino al otro y que toda la zona cubierta en cuatro pies de codornices? Hizo los cálculos. Eso serían 19,538,468,306,672 codornices. Y, naturalmente, fue motivo de grandes risas. Claro, 19 billones de codornices todas amontonadas.

Pero solo demostró su ignorancia. La Biblia hebrea no dice que fueron apiladas desde el suelo hacia arriba. Lo que la Escritura indica en el texto hebreo es que Dios sopló las codornices en el desierto desde el valle del Nilo; y todos los pájaros vinieron volando a unos dos codos sobre la tierra. Eso es lo que dice. Las codornices por lo general no se elevan a más de dos codos sobre el suelo; fueron llevadas allí por el Señor. Y era fácil para la gente alcanzarlas de esa manera, sólo tenían que estirar la mano. Las codornices fueron llegando, volando a ese nivel, hasta que todo el pueblo tuvo todo lo que quería.

Cuando la Biblia habla de ciencia, historia, matemáticas, sea lo que fuere de lo que la Biblia hable, es la Palabra de Dios. Y Dios es infalible; y también Su Palabra es así de infalible. Los críticos quieren burlarse de la Escritura; y sin embargo la Biblia es científicamente exacta, contiene los principios básicos de la ciencia. Usted podría tomar, por ejemplo, los elementos más básicos de la ciencia: el tiempo, la fuerza, la acción, el espacio y la materia. Herbert Spencer, quien murió en 1903, redujo todo a estas categorías. Dijo que todo lo que hay en el universo encaja en ellas, que esa es la matriz de la existencia.

Murió después de haber sido aclamado como un hombre brillante después de descubrir eso. Y no se dio cuenta que eso está en el primer versículo de la Biblia. “En el principio” -el tiempo- “creó” - la acción- “Dios” –la fuerza- “los cielos” -el espacio- y “la tierra” -la materia. La base de la existencia se encontraba en el primer versículo. El universo es una continuidad de tiempo, fuerza, acción, espacio, materia. Y uno no puede existir sin el otro, por lo tanto todo debe haber existido simultáneamente desde el principio. Todo tuvo que comenzar junto. La ciencia tiene que estar en esa matriz. No puede faltar ningún elemento de esta base o no tendríamos lo que tenemos en la actualidad. Y una vez que el universo había sido creado, sus procesos fueron diseñados para funcionar de una manera ordenada, toda la energía y la materia sostenidas por su interacción de modo que no se necesitara más creación.

Una vez que se genera el tiempo, la fuerza, la acción, el espacio y la materia, es todo lo que se necesita. Y Génesis 2:2 dice que Dios acabó la obra que hizo. Él lo hizo y lo concluyó. Todo a la vez, creó la matriz completa. No ha habido ninguna creación más desde entonces, ya que no se  necesita ninguna creación. La ciencia ha llamado al cese total de la actividad creativa la primera ley de la termodinámica o la ley de conservación de la masa y la energía, a la cual Einstein dedicó mucho tiempo. Es el principio científico más universal, cierto y básico de todos; y está allí mismo, en la Palabra de Dios. Él finalizó de hacer lo que hizo, terminó; lo hizo todo a la vez y listo, se conservaría por sí mismo debido a su propia naturaleza.

La segunda ley de la termodinámica es la ley del desorden creciente, que todo lo de ese sistema en la matriz se está agotando, desintegrándo y, finalmente, morirá. Y lo estamos viendo en términos muy claros. Toda la creación, dice Romanos 8, está gimiendo y gruñendo y esperando a que la maldición sea revertida. La ciencia no puede explicar la segunda ley de la termodinámica. No saben por qué todo tiende al desorden, todo tiende a decaer hacia la falta de vida. La Biblia es el único lugar donde usted puede acudir para ver una explicación. Y la explicación es una sola palabra: pecado... el pecado. No se puede ser científico si usted no cree en el pecado, porque no se puede explicar la naturaleza de la matriz de la existencia.

La Biblia es exacta en todo lo que dice. Dice que Él colgó la tierra sobre nada. Ya sea que usted esté hablando acerca de geología, geodesia, meteorología, fisiología, biología, antropología, astronomía, hidrología, cuando la Biblia habla, es exacta.

Y después ve cosas en la Biblia como la profecía. Por ejemplo, Ezequiel 28, una visión superlativa que muestra la exactitud de las Escrituras históricamente. Ezequiel 26 al 28. Una profecía de Ezequiel sobre la destrucción de la ciudad de Tiro. Tiro era una fortaleza fenicia, una ciudad bastante importante en la costa de Fenicia, hoy conocida como Palestina. Y la palabra del Señor vino a Ezequiel en el versículo 2 del capítulo 26 diciendo acerca de la destrucción del lugar. “Hijo de hombre, por cuanto dijo Tiro contra Jerusalén: Ea, bien; quebrantada está la que era puerta de las naciones; a mí se volvió; yo seré llena, y ella desierta.”

En otras palabras, ya que Tiro se burló de Jerusalén,  “por tanto, así ha dicho Jehová el Señor: He aquí yo estoy contra ti, oh Tiro, y haré subir contra ti muchas naciones, como el mar hace subir sus olas. Y demolerán los muros de Tiro, y derribarán sus torres; y barreré de ella hasta su polvo, y la dejaré como una peña lisa. Tendedero de redes será en medio del mar, porque Yo he hablado, dice Jehová el Señor; y será saqueada por las naciones. Y sus hijas que están en el campo serán muertas a espada; y sabrán que Yo soy Jehová. Porque así ha dicho Jehová el Señor: He aquí que del norte traigo Yo contra Tiro a Nabucodonosor, rey de Babilonia, rey de reyes, con caballos y carros y jinetes, y tropas y mucho pueblo. Matará a espada a tus hijas que están en el campo, y pondrá contra ti torres de sitio, y levantará contra ti baluarte, y escudo afirmará contra ti. Y pondrá contra ti arietes, contra tus muros, y tus torres destruirá con hachas. Por la multitud de sus caballos te cubrirá el polvo de ellos; con el estruendo de su caballería y de las ruedas y de los carros, temblarán tus muros, cuando entre por tus puertas como por portillos de ciudad destruida. Con los cascos de sus caballos hollará todas tus calles; a tu pueblo matará a filo de espada, y tus fuertes columnas caerán a tierra. Y robarán tus riquezas y saquearán tus mercaderías; arruinarán tus muros, y tus casas preciosas destruirán; y pondrán tus piedras y tu madera y tu polvo en medio de las aguas. Y haré cesar el estrépito de tus canciones, y no se oirá más el son de tus cítaras. Y te pondré como una peña lisa; tendedero de redes serás, y nunca más serás edificada; porque yo Jehová he hablado, dice Jehová el Señor. Así ha dicho Jehová el Señor a Tiro.”   

Bastante detallado. No es una especie de profecía general. Muy específica. Esta es una gran ciudad fenicia. Desde el siglo VII AC, controlaba Fenicia. Tenía fuertes murallas, de unos 150 metros de altura, de casi cinco metros de espesor. Y estaba floreciendo cuando Josué guió a Israel a Canaán. Hiram el primero era su rey. Él ayudó a David a construir el palacio. Y de acuerdo a 1 Crónicas 22, ayudó a Salomón a construir el templo.

Tres años después de que esta profecía fuera dada, Nabucodonosor la cercó durante 13 años. Eran ciudades amuralladas, todo lo que tenía que hacer era -si no podía entrar en la ciudad- cortar cualquier suministro que viniera a la ciudad y finalmente morirían de hambre. Le tomó 13 años -del 585 al 573. Por último, la ciudad se rindió ya que todos estaban muriendo. Y Nabucodonosor destruyó los muros y las torres; destruyó la ciudad e hizo cada cosa que Ezequiel dijo que haría; y por supuesto que no estaba leyendo a Ezequiel cuando lo hizo.

Entró en la ciudad. No encontró el botín. Pensó que iba a encontrar un botín, pero ellos habían utilizado su flota para sacarlo. Se llevaron todo a una isla frente a la costa a un kilómetro y medio de distancia y, por supuesto, en el capítulo 29 de Ezequiel, dijo que no obtendrían ningún botín. Exactamente lo que pasó. Cuando llegó allí, se habían llevado todos los objetos de valor a la isla, Nabucodonosor no tenía poderío naval para ir a buscarlo. La isla se convirtió en la nueva ciudad. Y floreció por 250 años.

Sólo una parte de la profecía se había cumplido. La parte acerca de Nabucodonosor, de la destrucción de las murallas, los asesinatos de la gente. Pero no todo se había terminado. Las ruinas estaban todavía allí, los escombros. Después de 250 años, llegó un joven de 24 años con el nombre de Alejandro Magno. Él tenía 33.000 hombres de infantería, 15.000 de caballería. Acababa de derrotar a los persas y estaba en camino a Egipto. Necesitaba suministros. Vino, pues, a la ciudad de Tiro -ahora en la isla- y envió un mensaje: "Quiero darles suministros a todos mis hombres, mis caballos y mi ejército". Y ellos dijeron: "Usted no tiene una flota y nosotros estamos en una isla, no le vamos a ayudar."

Eso no le gustó. Y no era bueno enfadar a Alejandro. Él no tenía una flota, por lo que decidió que tenía que conseguir una manera de ir a esa isla e hizo lo que Ezequiel, el profeta, dijo que se haría. Dijo que el lugar sería como una peña lisa y los escombros serían arrojados al mar. Bueno, ¿qué conquistador en su sano juicio haría eso? ¿Por qué perder el tiempo -una vez que ha conquistado el lugar-  recogiendo todo y tirándolo al océano? Toda la piedra y todo el resto de la misma. Pero eso es exactamente lo que tenía que suceder. Así que Alejandro lo hizo. Él tomó todos los escombros y construyó un istmo de más de medio kilómetro de largo y más de 60 metros de ancho hasta llegar a la isla con todos los desechos.

La isla se había fortalecido también con poderosas murallas que llegaban hasta el borde del mar. Y a medida que se acercaba, se dio cuenta de que tendría que superar esas paredes. Y con el fin de llevarlo a cabo, construyó enormes máquinas de asedio -de 165 metros de altura, según el registro. Le tomó siete meses. Él entró y asesinó a 8.000 personas; en un período de unos pocos meses  ejecutó a 7.000 más; vendió a más de 30.000 como esclavos y cumplió cada uno de los detalles de la profecía. Y aunque la ciudad de Jerusalén ha sido reconstruida 17 veces, Tiro nunca ha sido reconstruida. Y eso es exactamente lo que Dios dijo. Que no se edificaría más.

¿Y sabe a qué se dedican? Si va hoy en día, se dará cuenta lo que hacen. Ellos tienden redes de pesca, tal como lo decía. ¿Cuál es la probabilidad de eso? Aproximadamente una en 75 millones, de casualidad.

Por cierto, una ciudad hermana con el nombre de Sidón también recibió una profecía. Versículo 22 de Ezequiel 28: "Así ha dicho Jehová el Señor: He aquí yo estoy contra ti, oh Sidón, y en medio de ti seré glorificado; y sabrán que Yo soy Jehová, cuando haga en ella juicios, y en ella Me santifique. Enviaré a ella pestilencia y sangre en sus calles, y caerán muertos en medio de ella, con espada contra ella por todos lados; y sabrán que Yo soy Jehová. Y nunca más será a la casa de Israel espina desgarradora, ni aguijón que le dé dolor, en medio de cuantos la rodean y la menosprecian; y sabrán que Yo soy Jehová."

Será un caos sangriento. Es el centro del culto a Baal, a unos 36 kilómetros al norte de Tiro. La profecía habló de sangre en las calles, espadas por todas partes, pero ninguna profecía de destrucción final. Eso es lo que pasó. Sangre por todas partes, espadas por todas partes. Esa pobre ciudad fue sitiada y asediada una y otra vez y otra vez, pero aún es una ciudad. En 351 AC fue gobernada por Persia. Fue tomada en la revolución. Toda esperanza de salvar la ciudad había desaparecido. El pueblo estaba siendo atacado por los persas; y 40.000 de ellos prefirieron morir antes que someterse a la violencia persa, por lo que se prendieron fuego y se inmolaron con sus propias casas. La sangre fluyó en las calles una y otra vez. Esa ciudad, Sidón, fue tomada tres veces por los cruzados, tres veces por los musulmanes. En 1840, fue bombardeada por las fuerzas combinadas de Inglaterra, Francia y Turquía. Pero aún está allí porque Dios dijo que no sería destruida, todavía está allí.

Se puede estudiar la Biblia y predecir cosas que históricamente son absolutamente precisas. Ezequiel 30 predijo la destrucción de Egipto. Nahúm 1, la destrucción de Nínive. Isaías 13, la destrucción de Babilonia. Oseas 13, de la destrucción de Samaria. Ezequiel 25, la destrucción de Moab y Amón. Un matemático llamado Peter Stoner tomó once de las profecías con todos sus detalles; y calculó la probabilidad de que ocurrieran por casualidad: una en 5,76 veces, 10 a la quincuagésima novena potencia.

Usted dice: "¿Qué significa eso?" No sé. Ni siquiera puedo pensar así. ¿Cómo se calcula eso? ¿Cómo se entiende eso? Bueno, él lo estimó de esta manera: si todo el universo contuviera dos mil trillones de galaxias y cada galaxia tuviera cien mil millones de estrellas, serían todas las estrellas en todas las galaxias dos veces diez a la quinta potencia. Un número increíble. Este tipo de probabilidades simplemente no sucede. Así que cuando vea que la Biblia habla científica, geográfica, históricamente o lo que sea, es precisa.

Esta es la Palabra de Dios. ¿Y cuál es el beneficio? Volvamos a nuestro texto original y terminaremos allí. Segunda de Timoteo 3, ¿cuál es el beneficio de esto? "Toda la Escritura es inspirada por Dios, y útil para enseñar, para redargüir, para corregir, para instruir en justicia, a fin de que el hombre de Dios sea perfecto, enteramente preparado para toda buena obra." ¡Qué cosa tan estupenda! No sólo tenemos la palabra de Dios, sino que tenemos la Palabra de Dios que nos puede equipar completamente para toda buena obra. Tenemos la Palabra que cambia la vida.

¿Y cuál debería ser nuestra respuesta? En primer lugar, creerla. En segundo lugar, estudiarla. En tercer lugar, honrarla. Dios es exaltado por sobre Su nombre. Me encanta, "¡Oh, cuánto amo yo Tu ley", dijo David en el Salmo 119:97. Obedézcala, haga lo que ordena. Luche por ella. Judas 3, "contender ardientemente por la fe". Y predíquela, 2 Timoteo 4:2: "Predica la Palabra".

¿Se da cuenta de que durante su vida es probable que coma 150 cabezas de ganado? Tal vez un poco más. Va a comer por lo menos 3.000 pollos, conservadoramente, 225 corderos, 26 ovejas, 310 cerdos -solo en forma de tocino y jamón. Consumirá, usted solo, veintiséis hectáreas de cereales. Y comerá 50 acres de frutas y verduras. ¿Puedo recordarle lo que dijo Jesús? “No sólo de pan vivirá el hombre, sino de toda palabra que sale de la boca de Dios”. Mientras que usted está comiendo todo el resto, por favor pase un poco de tiempo en este libro... vamos a orar juntos.

Toda palabra que sale de la boca de Dios. ¡Qué declaración! Padre, nos estremece saber que eso es lo que nuestra Biblia es, palabras que se salieron de la boca de Dios. El Dios que no sólo conoce la historia, sino que la escribe, que no sólo comprende la ciencia sino que la creó, que no sólo comprende la dimensión espiritual, pero es esa realidad. ¡Oh Dios, qué tesoro! Ayúdanos a amar Tu Palabra, a honrar Tu Palabra, a creer Tu Palabra, a estudiar Tu Palabra, a defender Tu Palabra, a proclamar Tu Palabra. Haz que, mientras que estemos alimentándonos con el resto de las cosas en esta vida, no nos olvidemos que realmente vivimos de toda palabra que sale de Tu boca. Padre, ayúdanos a comprometernos a renovar nuestra devoción a Tu Palabra, pues en ella Tu estás revelado. Que nos demos cuenta de que el conocerte es a través de Tu Palabra; y por medio de las pruebas y experiencias de la vida en la que aplicamos esa Palabra. Satisface las necesidades de cada corazón, en el nombre de Cristo. Amén.

 

 

 

 

Disponible sobre el Internet en: www.gracia.org 
DERECHOS DE AUTOR 2014 Gracia a Vosotros
Usted podrá reproducir este contenido de Gracia a Vosotros sin fines comerciales de acuerdo con la  política de Derechos de Autor de Gracia a Vosotros.

// Función para cargar la transcripción
document.addEventListener('DOMContentLoaded', function() {
    // Depuración
    console.log('Script de transcripciones cargado');
    
    const btnTranscripcion = document.querySelector('[data-bs-target="#transcripcion1"]');
    const transcripcionContenido = document.querySelector('.transcripcion-contenido');
    
    // Depuración
    console.log('Botón:', btnTranscripcion);
    console.log('Contenedor:', transcripcionContenido);
    
    if (btnTranscripcion && transcripcionContenido) {
        btnTranscripcion.addEventListener('click', function() {
            console.log('Botón clickeado');
            transcripcionContenido.innerHTML = transcripciones.leccion1;
        });
    } else {
        console.log('No se encontraron los elementos necesarios');
    }
});
